# Generated by Django 3.0.4 on 2020-03-29 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('name', models.CharField(help_text='What sector does this business work in?  Coffee, retail, restaurant, etc', max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Sector of Business')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('name', models.CharField(help_text='Name of the business. 35 characters max.', max_length=35, primary_key=True, serialize=False, unique=True, verbose_name='Name')),
                ('status', models.BooleanField(help_text='Check for yes, leave blank for no', verbose_name='Currently open')),
                ('businessType', models.ForeignKey(help_text='Select what best describes this business.', on_delete=django.db.models.deletion.CASCADE, to='teamMembers.Sector', verbose_name='Type of Business')),
            ],
        ),
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='teamMembers.Business')),
                ('phoneNumber', phone_field.models.PhoneField(help_text='Store phone number.', max_length=31, null=True, verbose_name='Contact Number')),
                ('website', models.URLField(blank=True, help_text='Store website.', null=True, verbose_name='Website')),
                ('timeOpen', models.TimeField(help_text='What times does the store open?', null=True, verbose_name='Opening Time. In 24 hour time. Ex: 6:30 am is 06:30:00')),
                ('timeClose', models.TimeField(help_text='What times does the store close?', null=True, verbose_name='Closing Time. In 24 hour time. Ex: 7:45 pm is 19:45:00')),
                ('ordering', models.TextField(help_text='How can customers order products -i.e. online, phone, etc. 85 characters max', max_length=85, null=True, verbose_name='How Can Customers Order')),
                ('inStorePickUp', models.BooleanField(help_text='Can customer pick up in store? (check for yes, leave blank for no).', null=True, verbose_name='In store pickup')),
                ('deliveryOption', models.BooleanField(help_text='Can customers have items delivered via mail, driver, etc - i.e. someway the ordered item will arrive at their home (check for yes, leave blank for no).', null=True, verbose_name='Delivery Available')),
                ('specialNotes', models.TextField(blank=True, help_text='Additional details people should know? 80 characters max.', max_length=80, null=True, verbose_name='Special Notes')),
                ('ownerMessage', models.TextField(blank=True, help_text='If the owner wants to say something quote then here. 80 characters max.', max_length=80, null=True, verbose_name='Owner Message')),
                ('lastUpdatedDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last updated')),
                ('creationDate', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('approvedBy', models.ForeignKey(blank=True, default=None, help_text='Admin that approved for publishing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Approving_User', to=settings.AUTH_USER_MODEL, verbose_name='Entry approved by')),
                ('createdBy', models.ForeignKey(blank=True, default=None, help_text='User that created this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Creating_User', to=settings.AUTH_USER_MODEL, verbose_name='Entry created by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
