# Generated by Django 3.0.4 on 2020-03-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamMembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='specialNotes',
            field=models.TextField(blank=True, default=None, help_text='Additional details people should know? 80 characters max.', max_length=80, null=True, verbose_name='Special Notes'),
        ),
    ]
