# Generated by Django 3.0.4 on 2020-03-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamMembers', '0002_auto_20200329_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='ordering',
            field=models.TextField(help_text='How can customers order products -i.e. online, phone, etc. 250 characters max', max_length=250, null=True, verbose_name='How Can Customers Order'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='ownerMessage',
            field=models.TextField(blank=True, help_text='If the owner wants to say something quote then here. 250 characters max.', max_length=250, null=True, verbose_name='Owner Message'),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='specialNotes',
            field=models.TextField(blank=True, default=None, help_text='Additional details people should know? 250 characters max.', max_length=250, null=True, verbose_name='Special Notes'),
        ),
    ]
