# Generated by Django 3.0.4 on 2020-03-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamMembers', '0003_auto_20200329_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='name',
            field=models.CharField(help_text='What sector does this business work in?  Coffee, retail, restaurant, etc', max_length=35, primary_key=True, serialize=False, unique=True, verbose_name='Sector of Business'),
        ),
    ]
