# Generated by Django 3.0.4 on 2020-03-31 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamMembers', '0005_sector_testbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='testBS',
        ),
    ]
